"""K230 摄像头、显示和检测参数。"""


# ============================================================
# 一、多个程序共享的公共参数
# ============================================================


# ------------------------------------------------------------
# 摄像头与处理画面
# ------------------------------------------------------------

CAMERA_ID = 2
CAMERA_SOURCE_WIDTH = 1280
CAMERA_SOURCE_HEIGHT = 960
CAMERA_FPS = 30
CAMERA_PIXEL_FORMAT = "RGB888"

IMAGE_WIDTH = 640
IMAGE_HEIGHT = 480
IMAGE_CENTER_X = IMAGE_WIDTH // 2
IMAGE_CENTER_Y = IMAGE_HEIGHT // 2

# 当前画面需要同时水平镜像和垂直翻转，等效于旋转 180°。
CAMERA_HMIRROR = True
CAMERA_VFLIP = True


# ------------------------------------------------------------
# 目标追踪串口（uart_io.py）
# ------------------------------------------------------------

# 默认使用 UART1。K230 TX 接单片机 RX，K230 RX 接单片机 TX。
UART_ID = 1
UART_TX_PIN = 3
UART_RX_PIN = 4
UART_BAUDRATE = 115200
UART_SEND_PERIOD_MS = 10
UART_HANDSHAKE_PERIOD_MS = 100
UART_HANDSHAKE_POLL_INTERVAL_MS = 10

# ------------------------------------------------------------
# 摄像头显示输出（camera_io.py）
# ------------------------------------------------------------

DISPLAY_MODE_ST7701 = "st7701"
DISPLAY_MODE_VIRT = "virt"


# 板载 3.5 寸 ST7701 屏幕，供所有程序的 DISPLAY_TARGET_BOARD 使用。
BOARD_DISPLAY_MODE = DISPLAY_MODE_ST7701
BOARD_DISPLAY_WIDTH = 800
BOARD_DISPLAY_HEIGHT = 480
BOARD_DISPLAY_FPS = 30
BOARD_DISPLAY_TO_IDE = False
BOARD_DISPLAY_X = (BOARD_DISPLAY_WIDTH - IMAGE_WIDTH) // 2
BOARD_DISPLAY_Y = (BOARD_DISPLAY_HEIGHT - IMAGE_HEIGHT) // 2


# CanMV IDE 虚拟显示，供所有程序的 DISPLAY_TARGET_IDE 使用。
IDE_DISPLAY_MODE = DISPLAY_MODE_VIRT
IDE_DISPLAY_WIDTH = IMAGE_WIDTH
IDE_DISPLAY_HEIGHT = IMAGE_HEIGHT
IDE_DISPLAY_FPS = 30
IDE_DISPLAY_TO_IDE = True
IDE_DISPLAY_QUALITY = 80
IDE_DISPLAY_X = 0
IDE_DISPLAY_Y = 0


# ============================================================
# 二、各程序或模块特有的参数
# ============================================================


# ------------------------------------------------------------
# 蓝牙串口（bluetooth_uart.py）
# ------------------------------------------------------------

# 蓝牙串口默认使用 UART2。不同蓝牙模块的默认波特率可能不同。
BLUETOOTH_UART_ID = 2
BLUETOOTH_UART_TX_PIN = 11
BLUETOOTH_UART_RX_PIN = 12
BLUETOOTH_UART_BAUDRATE = 9600
BLUETOOTH_UART_SEND_PERIOD_MS = 0


# ------------------------------------------------------------
# 黑框白心方框检测与演示（tangle.py）
# ------------------------------------------------------------

# 在较低分辨率上检测，最终坐标自动映射回 IMAGE_WIDTH × IMAGE_HEIGHT。
RECTANGLE_DETECT_WIDTH = 320
RECTANGLE_DETECT_HEIGHT = 240

# 0 表示使用 Otsu 自动阈值；非 0 时使用给定灰度阈值。
RECTANGLE_BINARY_THRESHOLD = 0
RECTANGLE_USE_OTSU = True

RECTANGLE_MIN_AREA = 1500
RECTANGLE_MIN_WIDTH = 30
RECTANGLE_MIN_HEIGHT = 30
RECTANGLE_MAX_COUNT = 24

# 依次尝试多个轮廓拟合精度，兼顾清晰边缘和轻微运动模糊。
RECTANGLE_APPROX_RATIOS = (0.015, 0.025, 0.040, 0.060)

# 不再使用内部面积比例。沿四边形的四条边分别采样：内侧应明显比外侧亮。
RECTANGLE_EDGE_SAMPLE_COUNT = 5
RECTANGLE_EDGE_SAMPLE_OFFSET_RATIO = 0.05
RECTANGLE_EDGE_SAMPLE_MIN_OFFSET = 3.0
RECTANGLE_EDGE_SAMPLE_MAX_OFFSET = 8.0
RECTANGLE_MIN_MEAN_EDGE_CONTRAST = 20.0
RECTANGLE_MIN_SIDE_EDGE_CONTRAST = 18.0
RECTANGLE_EDGE_TARGET_CONTRAST = 80.0

RECTANGLE_MIN_CONFIDENCE = 0.60
RECTANGLE_STRONG_CONFIDENCE = 0.85

# 亮区边界没有得到强候选时才执行 Canny，降低正常帧的计算量。
RECTANGLE_USE_CANNY_FALLBACK = True
RECTANGLE_CANNY_LOW_RATIO = 0.40
RECTANGLE_CANNY_HIGH_RATIO = 1.20

# RectangleDetector.process() 的默认绘制样式。
RECTANGLE_DRAW_COLOR = (0, 255, 0)
RECTANGLE_DRAW_THICKNESS = 2
RECTANGLE_DRAW_CENTER_COLOR = (255, 255, 0)
RECTANGLE_DRAW_CENTER_RADIUS = 6

# 连续多少帧未检测到目标后，才判定目标丢失。
RECTANGLE_LOST_FRAME_LIMIT = 5

TANGLE_PRINT_INTERVAL = 10
TANGLE_GC_INTERVAL = 60
TANGLE_CENTER_CROSS_SIZE = 12


# ------------------------------------------------------------
# 方框四角循环应用（corner_cycle.py）
# ------------------------------------------------------------

CORNER_CYCLE_HOLD_MS = 3000
CORNER_CYCLE_MOVE_MS = 3000
CORNER_CYCLE_UART_SEND_PERIOD_MS = UART_SEND_PERIOD_MS
CORNER_CYCLE_PRINT_INTERVAL = 30
CORNER_CYCLE_GC_INTERVAL = 60
CORNER_CYCLE_NAMES = ("TL", "TR", "BR", "BL")
CORNER_CYCLE_COLORS = (
    (255, 0, 0),
    (0, 255, 0),
    (0, 128, 255),
    (255, 0, 255),
)
CORNER_CYCLE_OUTLINE_COLOR = (0, 255, 0)
CORNER_CYCLE_ACTIVE_COLOR = (255, 255, 0)
CORNER_CYCLE_CENTER_COLOR = (255, 255, 255)


# ------------------------------------------------------------
# 细铅笔线方框检测与演示（pencil_rectangle.py）
# ------------------------------------------------------------

# 细线在低分辨率缩放后容易消失，因此默认使用完整 640x480 画面检测。
PENCIL_RECTANGLE_DETECT_WIDTH = IMAGE_WIDTH
PENCIL_RECTANGLE_DETECT_HEIGHT = IMAGE_HEIGHT
PENCIL_RECTANGLE_USE_ADAPTIVE_THRESHOLD = True
PENCIL_RECTANGLE_ADAPTIVE_BLOCK_SIZE = 31
PENCIL_RECTANGLE_ADAPTIVE_C = 7
PENCIL_RECTANGLE_FALLBACK_THRESHOLD = 0
PENCIL_RECTANGLE_BLUR_KERNEL_SIZE = 3
# 实拍中铅笔线常有几个像素的断点。7x5 椭圆核可以连接小断点，
# 又比同尺寸矩形核更不容易把邻近物体粘到方框上。
PENCIL_RECTANGLE_CLOSE_KERNEL_WIDTH = 7
PENCIL_RECTANGLE_CLOSE_KERNEL_HEIGHT = 5
PENCIL_RECTANGLE_USE_ELLIPSE_CLOSE_KERNEL = True

PENCIL_RECTANGLE_MIN_AREA = 1500
PENCIL_RECTANGLE_MIN_WIDTH = 40
PENCIL_RECTANGLE_MIN_HEIGHT = 40
PENCIL_RECTANGLE_MAX_COUNT = 48
PENCIL_RECTANGLE_APPROX_RATIOS = (0.010, 0.018, 0.028, 0.045)

# 线宽由原始灰度图上的法线剖面估算，单位为原图像素。
PENCIL_RECTANGLE_MIN_BORDER_THICKNESS = 0.5
PENCIL_RECTANGLE_MAX_BORDER_THICKNESS = 25.0
PENCIL_RECTANGLE_MIN_THICKNESS_UNIFORMITY = 0.20
PENCIL_RECTANGLE_THICKNESS_TIE_PX = 0.50

# 在原始灰度图上，沿候选四边形每条边的法线测量暗线宽度。
PENCIL_RECTANGLE_PROFILE_SAMPLE_COUNT = 5
PENCIL_RECTANGLE_PROFILE_SAMPLE_MARGIN = 0.20
PENCIL_RECTANGLE_PROFILE_SCAN_RADIUS = 16
PENCIL_RECTANGLE_PROFILE_SEARCH_RADIUS = 6
PENCIL_RECTANGLE_PROFILE_END_COUNT = 4
PENCIL_RECTANGLE_PROFILE_DARK_RATIO = 0.50
PENCIL_RECTANGLE_MIN_EDGE_CONTRAST = 15

# confidence 只评价四边形几何，不再把线宽混入置信度。
# 35:25:15 会在检测器初始化时归一化。
PENCIL_RECTANGLE_STRAIGHTNESS_WEIGHT = 35
PENCIL_RECTANGLE_GEOMETRY_WEIGHT = 25
PENCIL_RECTANGLE_PARALLEL_WEIGHT = 15
PENCIL_RECTANGLE_MIN_STRAIGHTNESS_SCORE = 0.70
PENCIL_RECTANGLE_MIN_GEOMETRY_SCORE = 0.65
PENCIL_RECTANGLE_MIN_PARALLEL_SCORE = 0.80
PENCIL_RECTANGLE_MIN_CONFIDENCE = 0.75

PENCIL_RECTANGLE_DRAW_COLOR = (0, 255, 0)
PENCIL_RECTANGLE_DRAW_CENTER_COLOR = (255, 255, 0)
PENCIL_RECTANGLE_DRAW_THICKNESS = 2
PENCIL_RECTANGLE_DRAW_POINT_RADIUS = 5
PENCIL_RECTANGLE_PRINT_INTERVAL = 30
PENCIL_RECTANGLE_GC_INTERVAL = 60


# ------------------------------------------------------------
# 彩色光点检测与演示（color.py）
# ------------------------------------------------------------

# ColorSpotDetector() 不传参数时使用这些默认值。
COLOR_TARGET = "red"
COLOR_MIN_AREA = 2
COLOR_MAX_AREA = None
COLOR_MIN_CONFIDENCE = 0.0

# 将紧邻彩色区域的低饱和高亮像素并入目标，用于补全过曝发白的光点中心。
# 只在彩色掩膜附近接受高亮，避免把画面中所有白色区域都当作目标。
COLOR_INCLUDE_HIGHLIGHT = True
COLOR_HIGHLIGHT_MAX_SATURATION = 90
COLOR_HIGHLIGHT_MIN_VALUE = 220
COLOR_HIGHLIGHT_KERNEL_SIZE = 15

# OpenCV HSV：H 为 0..179，S/V 为 0..255。
# 红色跨越 H 的首尾，因此需要两个范围。
COLOR_PRESET_HSV_RANGES = {
    "red": (
        ((0, 80, 100), (15, 255, 255)),
        ((165, 80, 100), (179, 255, 255)),
    ),
    "green": (
        ((35, 80, 80), (85, 255, 255)),
    ),
    "blue": (
        ((90, 80, 80), (135, 255, 255)),
    ),
    "yellow": (
        ((20, 100, 100), (35, 255, 255)),
    ),
}

COLOR_DRAW_COLOR = (255, 255, 255)
COLOR_DRAW_RADIUS = 7
COLOR_DRAW_CROSS_SIZE = 10
COLOR_DEMO_GC_INTERVAL = 30


# ------------------------------------------------------------
# 寻路符号检测与演示（road.py）
# ------------------------------------------------------------

# 在较低分辨率上检测，再把坐标映射回原图。
ROAD_DETECT_WIDTH = 320
ROAD_DETECT_HEIGHT = 240

# 场地前景只有红色和黑色：二者的绿色通道都明显低于白色背景。
# 使用绿色通道 Otsu 代替 RGB->HSV 和两段红色阈值。
ROAD_FOREGROUND_MORPH_KERNEL_SIZE = 5
ROAD_ROUTE_MIN_AREA_RATIO = 0.002
ROAD_ROUTE_LEFT_MAX_RATIO = 0.32
ROAD_ROUTE_RIGHT_MIN_RATIO = 0.68
ROAD_ROUTE_DOWN_MIN_RATIO = 0.68
ROAD_ROUTE_MAX_TOP_RATIO = 0.75
ROAD_CROSS_TOP_MAX_RATIO = 0.32

# 五区域均使用 (x0, y0, x1, y1) 画面比例坐标。
ROAD_ROI_UP = (0.20, 0.00, 0.80, 0.32)
ROAD_ROI_DOWN = (0.20, 0.68, 0.80, 1.00)
ROAD_ROI_LEFT = (0.00, 0.25, 0.32, 0.75)
ROAD_ROI_RIGHT = (0.68, 0.25, 1.00, 0.75)
ROAD_ROI_CENTER = (0.25, 0.25, 0.75, 0.75)
# 只用于把选中主轮廓的方向占用率归一化为结构 confidence。
ROAD_ARM_MIN_OCCUPANCY = 0.025

# END 的中央路径只在结束符中心附近取点。
ROAD_PATH_CORRIDOR_HALF_WIDTH_RATIO = 0.12
ROAD_PATH_MIN_PIXELS_RATIO = 0.00020
ROAD_END_MIN_PATH_LENGTH_RATIO = 0.12

# 黑色双排虚线结束符。
# RGB 三个通道都不超过该值时视为黑色，不再依赖 HSV。
ROAD_BLACK_MAX_VALUE = 90
ROAD_BLACK_MORPH_KERNEL_SIZE = 3
ROAD_DASH_MIN_AREA_RATIO = 0.00039
ROAD_DASH_MIN_WIDTH_RATIO = 0.025
ROAD_DASH_MAX_WIDTH_RATIO = 0.20
ROAD_DASH_MIN_HEIGHT_RATIO = 0.018
ROAD_DASH_MAX_HEIGHT_RATIO = 0.16
ROAD_DASH_MIN_ASPECT_RATIO = 0.65
ROAD_DASH_MAX_ASPECT_RATIO = 4.50
ROAD_DASH_MIN_FILL_RATIO = 0.35
ROAD_DASH_MIN_COUNT_PER_ROW = 3
ROAD_DASH_ROW_TOLERANCE_RATIO = 0.045
ROAD_DASH_MIN_ROW_SEPARATION_RATIO = 0.07
ROAD_DASH_MAX_ROW_SEPARATION_RATIO = 0.30
ROAD_DASH_MIN_HORIZONTAL_OVERLAP = 0.55

# 绘制参数。颜色元组直接写入 RGB888 画面。
ROAD_DRAW_SEGMENT_COLOR = (0, 255, 0)
ROAD_DRAW_ENDPOINT_COLOR = (255, 255, 0)
ROAD_DRAW_INTERSECTION_COLOR = (255, 255, 255)
ROAD_DRAW_DASH_COLOR = (0, 255, 255)
ROAD_DRAW_TEXT_COLOR = (255, 255, 255)
ROAD_DRAW_THICKNESS = 2
ROAD_DRAW_POINT_RADIUS = 6
ROAD_DRAW_FONT_SCALE = 0.60
ROAD_DEMO_GC_INTERVAL = 30


# ------------------------------------------------------------
# 数字识别与演示（num.py）
# ------------------------------------------------------------

DIGIT_TEMPLATE_DIR = "/digit_templates"
DIGIT_TEMPLATE_DIR_CANDIDATES = (
    DIGIT_TEMPLATE_DIR,
    "/sdcard/digit_templates",
)

DIGIT_NORMALIZED_WIDTH = 48
DIGIT_NORMALIZED_HEIGHT = 64
DIGIT_NORMALIZED_MARGIN = 4

DIGIT_MIN_AREA = 150
DIGIT_MAX_AREA = 50000
DIGIT_MIN_WIDTH = 5
DIGIT_MIN_HEIGHT = 20
DIGIT_MAX_WIDTH = 250
DIGIT_MAX_HEIGHT = 400
DIGIT_MIN_ASPECT_RATIO = 0.05
DIGIT_MAX_ASPECT_RATIO = 1.80
DIGIT_MAX_COUNT = 12

DIGIT_MATCH_THRESHOLD = 0.35

# 全图粗检测预处理。
DIGIT_BLUR_KERNEL_SIZE = 5
DIGIT_MORPH_KERNEL_SIZE = 3

# 候选 ROI 局部断笔修复。
DIGIT_LOCAL_BLUR_KERNEL_SIZE = 3
DIGIT_LOCAL_MORPH_KERNEL_SIZE = 5
DIGIT_ROI_MARGIN_DIVISOR = 12
DIGIT_ROI_MIN_MARGIN = 2

# 候选过滤、同行选择和结构分类。
DIGIT_MIN_FILL_RATIO = 0.18
DIGIT_FRAME_BORDER_MARGIN = 0
DIGIT_LINE_CENTER_TOLERANCE_RATIO = 0.42
DIGIT_LINE_MIN_HEIGHT_RATIO = 0.68
DIGIT_SHAPE_MAX_DISTANCE = 2.20
DIGIT_BROKEN_EIGHT_MIN_ASPECT_RATIO = 1.32
DIGIT_STRONG_TEMPLATE_THRESHOLD = 0.70

DIGIT_DRAW_RECOGNIZED_COLOR = (0, 255, 0)
DIGIT_DRAW_UNKNOWN_COLOR = (255, 0, 0)
DIGIT_DRAW_TEXT_COLOR = (255, 255, 0)
DIGIT_DRAW_THICKNESS = 2
DIGIT_DRAW_SUMMARY = True
DIGIT_DEMO_PRINT_INTERVAL = 30
DIGIT_DEMO_GC_INTERVAL = 30
